file_auto_uploader:
  is_active: true
  file_type:
    [
      image/png,
      image/gif,
      image/jpeg,
      image/svg,
      image/jpg,
      application/pdf,
      application/zip,
    ]
  file_size: "20011000"
  is_public: true
maintain_mode:
  is_active: falses
error_saver: true
